//
// Generated file, do not edit! Created by nedtool 4.6 from PacketOfPackets.msg.
//

#ifndef _PACKETOFPACKETS_M_H_
#define _PACKETOFPACKETS_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "Packet_m.h"
// }}

/**
 * Class generated from <tt>PacketOfPackets.msg:24</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet PacketOfPackets extends Packet
 * {
 * }
 * </pre>
 */
class PacketOfPackets : public ::Packet
{
  protected:

  private:
    void copy(const PacketOfPackets& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PacketOfPackets&);

  public:
    PacketOfPackets(const char *name=NULL, int kind=0);
    PacketOfPackets(const PacketOfPackets& other);
    virtual ~PacketOfPackets();
    PacketOfPackets& operator=(const PacketOfPackets& other);
    virtual PacketOfPackets *dup() const {return new PacketOfPackets(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, PacketOfPackets& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PacketOfPackets& obj) {obj.parsimUnpack(b);}


#endif // ifndef _PACKETOFPACKETS_M_H_

